<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationTitle>LumDb Explorer</ApplicationTitle>
    <Product>LumDb Explorer</Product>
    <Version>2.1.0</Version>
    <Description>Browse, create, and edit LumDb databases.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LumDbEngine\LumDbEngine.csproj" />
  </ItemGroup>

</Project>